build:
	# TODO 
	gcc pb1.c -o p1
	gcc pb2.c -o p2
	gcc pb3.c -o p3

run-p1:      # nume necesar
	./p1
run-p2:      # nume necesar
	./p2
run-p3:      # nume necesar 
	./p3

clean:		 # nume necesar
	rm p1 p2 p3
